spring:
  config:
    activate:
      on-profile: dev # 프로필 이름을 dev로 변경
  # 데이터베이스 정보 (Environment Variables로 대체)
  datasource:
    url: ${DATASOURCE_URL} # 예: jdbc:postgresql://your-dev-db-host:5432/your-db
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver

  # JPA 설정
  jpa:
    hibernate:
      ddl-auto: update # 개발 환경에서는 update 또는 validate가 적절
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  # JWT 설정 (Environment Variables로 대체)
  jwt:
    secret: ${JWT_SECRET}
    expiration: 3600000 # 1시간
    refresh-expiration: 604800000 # 7일
    redirect:
      onboarding: https://dev.loventure.com/onboarding # 개발용 프론트엔드 주소
      base: https://dev.loventure.com/home

  # OAuth2 클라이언트 설정 (Environment Variables로 대체)
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope:
              - profile
              - email
          kakao:
            client-id: ${KAKAO_CLIENT_ID}
            client-secret: ${KAKAO_CLIENT_SECRET}
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            authorization-grant-type: authorization_code
            scope:
              - profile_nickname
              - account_email
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kauth.kakao.com/v2/user/me
            user-name-attribute: id