spring:
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password: 
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
  jwt:
    secret: fa0e515481049208926bf3199115485a6321c9f4138da7725bb1eecd8f67c5b6
    expiration: 3600000
    refresh-expiration: 86400000
    redirect:
      onboarding: https://loventure.us/onboarding
      base: https://loventure.us/home
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: test-google-client-id
            client-secret: test-google-client-secret
            scope:
              - profile
              - email
          kakao:
            client-id: test-kakao-client-id
            client-secret: test-kakao-client-secret
            redirect-uri: http://localhost/login/oauth2/code/kakao
            authorization-grant-type: authorization_code
            scope:
              - profile_nickname
              - account_email
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kauth.kakao.com/v2/user/me
            user-name-attribute: id

server:
  port: 8080


