spring:
  # 데이터베이스 정보 (Environment Variables로 대체)
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  # JPA 설정
  jpa:
    hibernate:
      ddl-auto: update # 개발 환경에서는 update 또는 validate가 적절
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  # JWT 설정 (Environment Variables로 대체)
  jwt:
    secret: ${JWT_SECRET}
    expiration: 600000 # 10분
    refresh-expiration: 1209600000 # 14일
    redirect:
      onboarding: https://loventure.us/onboarding/me # 개발용 프론트엔드 주소
      base: https://loventure.us/home

  # OAuth2 클라이언트 설정 (Environment Variables로 대체)
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            redirect-uri: https://api.loventure.us/api/auth/login/oauth2/code/google
            scope:
              - profile
              - email
          kakao:
            client-id: ${KAKAO_CLIENT_ID}
            client-secret: ${KAKAO_CLIENT_SECRET}
            redirect-uri: https://api.loventure.us/api/auth/login/oauth2/code/kakao
            authorization-grant-type: authorization_code
            scope:
              - profile_nickname
              - account_email
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kauth.kakao.com/v2/user/me
            user-name-attribute: id

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      enabled: true
      show-details: always
      show-components: always
  health:
    db:
      enabled: true
    diskspace:
      enabled: true
    defaults:
      enabled: true
  security:
    enabled: false